# dtype is needed for writing node
produce:
  - tag: "flux"
    node: "ns=2;s=模拟器示例.函数.Ramp1"
    dtype: "UInt64"
  - tag: "fluxVice"
    node: "ns=2;s=模拟器示例.函数.Random2"
    dtype: "Float"
  - tag: "switch"
    node: "ns=2;s=模拟器示例.函数.switch"
    dtype: "Boolean"
  - tag: "switchVice"
    node: "ns=2;s=模拟器示例.函数.switchVice"
    dtype: "Boolean"
  - tag: "setpoint"
    node: "ns=2;s=模拟器示例.函数.setpoint"
    dtype: "Double"
  - tag: "setpointVice"
    node: "ns=2;s=模拟器示例.函数.setpointVice"
    dtype: "Double"
test:
  - tag: "testBool"
    node: "ns=2;s=模拟器示例.函数.bool"
    dtype: "Boolean"
  - tag: "testDouble"
    node: "ns=2;s=模拟器示例.函数.test"
    dtype: "Double"
  - tag: "ramp1"
    node: "ns=2;s=模拟器示例.函数.Ramp1"

